2025-07-24 14:23:17,347:ERROR:Error sending invoices to Django: 400 Client Error: Bad Request for url: http://127.0.0.1:8000/api/users/invoices/
2025-07-24 14:25:27,591:ERROR:Error sending invoices to Django: 400 Client Error: Bad Request for url: http://127.0.0.1:8000/api/users/invoices/
2025-07-24 15:14:54,358:ERROR:Login failed: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/generate_token_agent/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013C89EC0050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-07-24 15:15:03,805:ERROR:Login failed: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/generate_token_agent/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013C89EBCCD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-07-24 15:15:50,426:ERROR:Error sending receipts to Django: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8000/api/users/receipts/
